### ISSUE TITLE
Look into manual triggering of GitHub action

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks-IT/imagecentral-dashboard#8]

**Comment by zaro0508** [comment]
NVM.  i think it's not available.. https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504

**Comment by thomasyu888** [comment]
I think I can add another condition like on push to master...

**Comment by zaro0508** [comment]
i think this is available now, correct @thomasyu888
